package in.hundredmph.api.domain.session;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

/**
 * A session that actually happened.
 *
 * <p>Only completed work is stored. A scheduled-but-not-yet-done session is not
 * a fact, it is the plan — the weekly template already says that, and writing
 * rows for it would mean inventing and then correcting the future.
 *
 * <p>The id is generated by the client at the moment of the tap and used as the
 * document id, so a retry after a dropped connection writes the same document
 * rather than a duplicate. The (user, date) index is the backstop.
 */
@Document(collection = "session_logs")
@CompoundIndex(name = "session_user_date_idx", def = "{'user_id': 1, 'local_date': 1}", unique = true)
public class SessionLog {

    @Id
    private String id;

    @Indexed
    @Field("user_id")
    private String userId;

    @Field("program_id")
    private String programId;

    @Field("session_type_id")
    private String sessionTypeId;

    /** The member's own calendar day — never derived from a UTC timestamp. */
    @Field("local_date")
    private LocalDate localDate;

    /** "guided" (ticked off exercise by exercise) or "logged" (marked done). */
    private String source;

    /** What was actually performed, when the session was done guided. */
    @Field("completed_exercises")
    private List<CompletedExercise> completedExercises = List.of();

    @Field("duration_min")
    private Integer durationMin;

    private String note;

    @Field("completed_at")
    private Instant completedAt;

    @Field("created_at")
    private Instant createdAt;

    public record CompletedExercise(String exerciseId, boolean completed, String note) {}

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }

    public String getProgramId() { return programId; }
    public void setProgramId(String programId) { this.programId = programId; }

    public String getSessionTypeId() { return sessionTypeId; }
    public void setSessionTypeId(String sessionTypeId) { this.sessionTypeId = sessionTypeId; }

    public LocalDate getLocalDate() { return localDate; }
    public void setLocalDate(LocalDate localDate) { this.localDate = localDate; }

    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }

    public List<CompletedExercise> getCompletedExercises() { return completedExercises; }
    public void setCompletedExercises(List<CompletedExercise> completedExercises) {
        this.completedExercises = completedExercises == null ? List.of() : completedExercises;
    }

    public Integer getDurationMin() { return durationMin; }
    public void setDurationMin(Integer durationMin) { this.durationMin = durationMin; }

    public String getNote() { return note; }
    public void setNote(String note) { this.note = note; }

    public Instant getCompletedAt() { return completedAt; }
    public void setCompletedAt(Instant completedAt) { this.completedAt = completedAt; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }
}
